###
POST http://localhost:8080/api/v1/auth/reset
Content-Type: application/json

{
    "username": "T66K6qm4Tqd8KCIrTrVP1w=="
}

###
POST http://localhost:8080/api/v1/auth/reset
Content-Type: application/json

{
    "username": "+hxNF5knFjVZ3kEvCx7eoQ=="
}

###
POST http://localhost:8080/api/v1/auth/reset
Content-Type: application/json

{
    "username": "T66K6qm4Tqd81CIrTrVP1w=="
}